read_database:
  host: 127.0.0.1
  port: 5432
  username: dealership
  password: password
  db_name: dealership
write_database:
  host: 127.0.0.1
  port: 5432
  username: dealership
  password: password
  db_name: dealership