version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; pipenv run alembic upgrade head; pipenv run uvicorn app.server:app --host 0.0.0.0'
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dealership
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dealership

volumes:
  postgres_data: