"""Initial migration

Revision ID: 28298af6609f
Revises: 24418d757cc6
Create Date: 2023-09-15 02:06:28.514100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28298af6609f'
down_revision: Union[str, None] = '24418d757cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_meeting_user_uc', 'participants', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_meeting_user_uc', 'participants', ['meeting_id', 'user_id'])
    # ### end Alembic commands ###
