"""Initial migration

Revision ID: 287b8eebe4c5
Revises: 6779a76f5158
Create Date: 2023-09-13 23:01:05.874379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287b8eebe4c5'
down_revision: Union[str, None] = '6779a76f5158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('custom_item_number', sa.Float(), nullable=True))
    op.drop_constraint('custom_items_creator_id_fkey', 'custom_items', type_='foreignkey')
    op.drop_column('custom_items', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_items', sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('custom_items_creator_id_fkey', 'custom_items', 'users', ['creator_id'], ['id'])
    op.drop_column('checks', 'custom_item_number')
    # ### end Alembic commands ###
