"""Initial migration

Revision ID: 42d850993e8c
Revises: f699bba15641
Create Date: 2023-09-13 02:18:17.878000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d850993e8c'
down_revision: Union[str, None] = 'f699bba15641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('meeting_id', sa.UUID(), nullable=True))
    op.add_column('feedback', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint('_participant_comment_uc', 'feedback', type_='unique')
    op.create_unique_constraint('_user_meeting_uc', 'feedback', ['user_id', 'meeting_id'])
    op.drop_constraint('feedback_participant_id_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'meetings', ['meeting_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'users', ['user_id'], ['id'])
    op.drop_column('feedback', 'participant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('participant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_participant_id_fkey', 'feedback', 'participants', ['participant_id'], ['id'])
    op.drop_constraint('_user_meeting_uc', 'feedback', type_='unique')
    op.create_unique_constraint('_participant_comment_uc', 'feedback', ['participant_id'])
    op.drop_column('feedback', 'user_id')
    op.drop_column('feedback', 'meeting_id')
    # ### end Alembic commands ###
