"""Initial migration

Revision ID: 5ecec846b876
Revises: d8abdd969fe4
Create Date: 2023-09-15 03:34:24.415210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecec846b876'
down_revision: Union[str, None] = 'd8abdd969fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_participant_custom_item_uc', 'checks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_participant_custom_item_uc', 'checks', ['participant_id', 'custom_item_id'])
    # ### end Alembic commands ###
