"""Initial migration

Revision ID: 5fd8457e9ec5
Revises: 8bb8c3ed48dc
Create Date: 2023-09-14 00:47:09.083840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd8457e9ec5'
down_revision: Union[str, None] = '8bb8c3ed48dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('custom_items_creator_id_fkey', 'custom_items', type_='foreignkey')
    op.drop_column('custom_items', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_items', sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('custom_items_creator_id_fkey', 'custom_items', 'participants', ['creator_id'], ['id'])
    # ### end Alembic commands ###
