"""Initial migration

Revision ID: 6779a76f5158
Revises: 42d850993e8c
Create Date: 2023-09-13 22:47:58.033672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6779a76f5158'
down_revision: Union[str, None] = '42d850993e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_items', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'custom_items', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_items', type_='foreignkey')
    op.drop_column('custom_items', 'creator_id')
    # ### end Alembic commands ###
