"""Initial migration

Revision ID: 7c832ed6acf1
Revises: 5fd8457e9ec5
Create Date: 2023-09-14 02:38:32.328769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c832ed6acf1'
down_revision: Union[str, None] = '5fd8457e9ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'custom_item_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('custom_item_number', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
