"""Initial migration

Revision ID: c3ba8e02d4cd
Revises: 5ecec846b876
Create Date: 2023-09-15 03:38:19.768340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ba8e02d4cd'
down_revision: Union[str, None] = '5ecec846b876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_participant_custom_item_uc', 'checks', ['participant_id', 'custom_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_participant_custom_item_uc', 'checks', type_='unique')
    # ### end Alembic commands ###
