"""Initial migration

Revision ID: e142eb788e66
Revises: 287b8eebe4c5
Create Date: 2023-09-13 23:05:35.870432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e142eb788e66'
down_revision: Union[str, None] = '287b8eebe4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_items', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'custom_items', 'participants', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_items', type_='foreignkey')
    op.drop_column('custom_items', 'creator_id')
    # ### end Alembic commands ###
