"""Initial migration

Revision ID: e759c64256e3
Revises: c3ba8e02d4cd
Create Date: 2023-09-15 04:08:37.831774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e759c64256e3'
down_revision: Union[str, None] = 'c3ba8e02d4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_participant_custom_item_uc', 'checks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_participant_custom_item_uc', 'checks', ['participant_id', 'custom_item_id'])
    # ### end Alembic commands ###
